version: '3.1'

services:
  postgres:
    image: postgis/postgis:12-3.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

